# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/roozbeh/vivado/FIFO_ip/FIFO_ip.cache/wt [current_project]
set_property parent.project_path /home/roozbeh/vivado/FIFO_ip/FIFO_ip.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/roozbeh/vivado/FIFO_ip/FIFO_ip.srcs [current_project]
read_vhdl -library xil_defaultlib {
  /home/roozbeh/vivado/FIFO_ip/FIFO_ip.srcs/sources_1/new/FIFO.vhd
  /home/roozbeh/vivado/FIFO_ip/FIFO_ip.srcs/sources_1/new/axis_tiny_fifo.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top axis_tiny_fifo -part xc7z020clg484-1


write_checkpoint -force -noxdef axis_tiny_fifo.dcp

catch { report_utilization -file axis_tiny_fifo_utilization_synth.rpt -pb axis_tiny_fifo_utilization_synth.pb }
