# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/zakhar/motor_1/motor_1.tmp/pwm_v2_0_project/pwm_v2_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/zakhar/motor_1/motor_1.tmp/pwm_v2_0_project/pwm_v2_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/zakhar/ip_repo/encoder_2.0
  c:/Users/zakhar/ip_repo/pwm_2.0
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  c:/users/zakhar/ip_repo/pwm_2.0/hdl/pwm_v2_0_S00_AXI.vhd
  c:/users/zakhar/ip_repo/pwm_2.0/hdl/pwm_v2_0.vhd
}
synth_design -top pwm_v2_0 -part xc7z010clg400-1
write_checkpoint -noxdef pwm_v2_0.dcp
catch { report_utilization -file pwm_v2_0_utilization_synth.rpt -pb pwm_v2_0_utilization_synth.pb }
