# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/roozbeh/git/pwmTest/pwmTest.cache/wt [current_project]
set_property parent.project_path /home/roozbeh/git/pwmTest/pwmTest.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths /home/roozbeh/vivado/FIFO_ip [current_project]
add_files /home/roozbeh/git/pwmTest/pwmTest.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/roozbeh/git/pwmTest/pwmTest.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /home/roozbeh/git/pwmTest/pwmTest.srcs/sources_1/bd/design_1/design_1.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/roozbeh/git/pwmTest/pwmTest.srcs/constrs_1/new/test.xdc
set_property used_in_implementation false [get_files /home/roozbeh/git/pwmTest/pwmTest.srcs/constrs_1/new/test.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top design_1 -part xc7z020clg484-1


write_checkpoint -force -noxdef design_1.dcp

catch { report_utilization -file design_1_utilization_synth.rpt -pb design_1_utilization_synth.pb }
