# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test.xdc

# Block Designs: bd/design_1/design_1.bd
# Block Designs: The module: 'design_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/design_1/ip/design_1_AXI_PWM_0_0/design_1_AXI_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI_PWM_0_0 || ORIG_REF_NAME==design_1_AXI_PWM_0_0}]

# XDC: bd/design_1/design_1_ooc.xdc
